<template>
      <div class="three">
        <!-- <img class="logo" :src="Logo" alt="">
        <div class="box">
          <img class="more" :src="Baob" @click="show" alt="">
          <div class="port" v-if="isshow">
            <li><a href="#/web">Portfolio</a></li>
            <li><a href="#/web">Home</a></li>
            <li><a href="#/web">Blog</a></li>
            <li><a href="#/web">Our services</a></li>
            <li><a href="#/web">Resources</a></li>
          </div>
        </div> -->
        <Head></Head>
      <div class="head">
        <div></div>
        <div>About Us</div>
        <div></div>
      </div>
      <div class="main">
        <p>Chameleon aims to utilise the Internet of Things (IoT), which is an ecosystem consisting of web-enabled smart devices such as phones, suburban traffic systems and domestic appliances, that all use embedded systems, such as processors, sensors, and communication hardware, to collect, send and act on data they acquire from their environments. </p>
        <p>We hope to harness the data generated by these systems through researching, creating, testing, documenting and deploying IoT-based solutions which aim to enhance life through the application of smart city technologies including: the building of smarter cities, homes, transportation, and energy management systems.</p>
        <p>If you would like to learn more about what this looks like in practice, navigate to our Portfolio section!</p>
        <div class="li-container">
          <div class="li">
            <div class="imgtxt-container">
              <img :src="Building" alt="" />
              <div class="img-txt">50,000+</div>
            </div>
            <div class="imgtxt-container">
              <img :src="Hand" alt="" />
              <div class="img-txt">10,000+</div>
            </div>
          </div>
          <div class="li liRight">
            <div class="imgtxt-container">
              <img :src="User" alt="" />
              <div class="img-txt">43,850</div>
            </div>
            <div class="imgtxt-container">
              <img :src="Globe" alt="" />
              <div class="img-txt">12</div>
            </div>        
          </div>
        </div>
         <div class="video-p1">
          <iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/2006242/sp/200624200/embedIframeJs/uiconf_id/32026212/partner_id/2006242?iframeembed=true&playerId=kaltura_player&entry_id=1_dh8w0mac&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_sx57bihq" width="500" height="281" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *"  frameborder="0" title="Chameleon Company Projects Showcase (T1 2022)"></iframe>
        </div>
      </div>
    </div>
</template>

<script>
const Hand = require("@/assets/images/hand.png");
const Building = require("@/assets/images/building.png");
const Globe = require("@/assets/images/globe.png");
const User = require("@/assets/images/user.png");

const Logo= require("@/assets/images/logo2.png");
const Baob= require("@/assets/images/menu.png");
import Head from "./Head.vue"
export default {
  name: "AboutUs",
  data() {
    return {
      Hand,
      Building,
      Globe,
      User,
      Logo,
      Baob,
      isshow:false,
    };
  },
  mounted() {},
  methods: {
    show(){
      if(this.isshow){
        this.isshow=false;
      }else{
        this.isshow=true;
      }
    }
    },
  components:{
    Head
  }
};
</script>

<style scoped lang="scss">
.three {
  .port{
    position: absolute;
    right: 10px;
    margin-top: 50px;
  }
  padding: 10px 40px;
  .box{
    float: right;
  }
  .port li{
    list-style: none;

    a{
      text-decoration: none;
      color:black;
    }
  }
 
  .logo{
    width: 80px;
    height: 80px;
  }
  .more{
  width: 40px;
  height: 40px;
  float: right;
  margin-top: 10px;
  }
  .head {
    display: flex;
    align-items: center;
    div:first-child {
      flex: 1;
      height: 2px;
      background: #99c854;
    }
    div:nth-child(2) {
      padding: 0 20px;
      font-size: 30px;
      font-weight: bold;
    }
    div:last-child {
      flex: 1;
      height: 2px;
      background: #99c854;
    }
  }
  .main {
    margin-top: 40px;
    font-size: 20px;
    font-family: 'Poppins', sans-serif;
    font-weight: 500;

    p {
      font-size: 18px;
      font-family: 'Poppins', sans-serif;
      font-weight: 500;
      text-indent: 2em;
    }
   
   .li{
    float: left;
    margin-top: 2%;
    width:50%;
   }
   
   .imgtxt-container{
    img{
        width:80px;
        height:80px;
    }
    //  float: left;
     text-align: center;
     margin-right: 100px;
   }
   .img-txt{
     margin-top: 20px;
   }

   .li-container{
     margin-left: 20%;
   }
   .video-p1 {
      width:100%;
      min-height:200px;
      margin-top:40px;

    } 
    .video-p1 iframe {
      width:100%;
      min-height:200px;
    } 
  }  
}
</style>

